# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protocol/game.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protocol/game.proto',
  package='game',
  syntax='proto3',
  serialized_options=b'Z\023protocol/logic/auth',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13protocol/game.proto\x12\x04game\"-\n\x08LoginReq\x12\x0f\n\x07\x61\x63\x63ount\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"e\n\tLoginResp\x12!\n\tuser_info\x18\x01 \x01(\x0b\x32\x0e.game.UserInfo\x12\x0f\n\x07\x62\x61lance\x18\x02 \x01(\x03\x12\r\n\x05token\x18\n \x01(\t\x12\x15\n\rrefresh_token\x18\x0b \x01(\t\"\\\n\x08UserInfo\x12\x0f\n\x07user_id\x18\x01 \x01(\x04\x12\x0f\n\x07\x61\x63\x63ount\x18\x02 \x01(\t\x12\x10\n\x08nickname\x18\x03 \x01(\t\x12\x1c\n\x06gender\x18\x04 \x01(\x0e\x32\x0c.game.Gender\"`\n\x0bRegisterReq\x12\x0f\n\x07\x61\x63\x63ount\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x10\n\x08nickname\x18\x03 \x01(\t\x12\x1c\n\x06gender\x18\x04 \x01(\x0e\x32\x0c.game.Gender\"\x1f\n\x0cRegisterResp\x12\x0f\n\x07user_id\x18\x01 \x01(\x04\"\x13\n\x11GetOnlineUsersReq\"3\n\x12GetOnlineUsersResp\x12\x1d\n\x05users\x18\x01 \x03(\x0b\x32\x0e.game.UserInfo\"}\n\tBattleMsg\x12/\n\x08msg_type\x18\x01 \x01(\x0e\x32\x1d.game.BattleMsg.BattleMsgType\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\".\n\rBattleMsgType\x12\r\n\tTYPE_NONE\x10\x00\x12\x0e\n\nTYPE_FIGHT\x10\x01\"#\n\rBattleLiteReq\x12\x12\n\ntarget_uid\x18\x01 \x01(\x04\".\n\x0e\x42\x61ttleLiteResp\x12\x1c\n\x03msg\x18\x01 \x03(\x0b\x32\x0f.game.BattleMsg*+\n\x06Gender\x12\x0b\n\x07UNKNOWN\x10\x00\x12\n\n\x06\x46\x45MALE\x10\x01\x12\x08\n\x04MALE\x10\x02\x32\xae\x01\n\x04Game\x12*\n\x05Login\x12\x0e.game.LoginReq\x1a\x0f.game.LoginResp\"\x00\x12\x33\n\x08Register\x12\x11.game.RegisterReq\x1a\x12.game.RegisterResp\"\x00\x12\x45\n\x0eGetOnlineUsers\x12\x17.game.GetOnlineUsersReq\x1a\x18.game.GetOnlineUsersResp\"\x00\x32\x43\n\x06\x42\x61ttle\x12\x39\n\nBattleLite\x12\x13.game.BattleLiteReq\x1a\x14.game.BattleLiteResp\"\x00\x42\x15Z\x13protocol/logic/authb\x06proto3'
)

_GENDER = _descriptor.EnumDescriptor(
  name='Gender',
  full_name='game.Gender',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FEMALE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MALE', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=690,
  serialized_end=733,
)
_sym_db.RegisterEnumDescriptor(_GENDER)

Gender = enum_type_wrapper.EnumTypeWrapper(_GENDER)
UNKNOWN = 0
FEMALE = 1
MALE = 2


_BATTLEMSG_BATTLEMSGTYPE = _descriptor.EnumDescriptor(
  name='BattleMsgType',
  full_name='game.BattleMsg.BattleMsgType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TYPE_NONE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TYPE_FIGHT', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=557,
  serialized_end=603,
)
_sym_db.RegisterEnumDescriptor(_BATTLEMSG_BATTLEMSGTYPE)


_LOGINREQ = _descriptor.Descriptor(
  name='LoginReq',
  full_name='game.LoginReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='account', full_name='game.LoginReq.account', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='password', full_name='game.LoginReq.password', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=74,
)


_LOGINRESP = _descriptor.Descriptor(
  name='LoginResp',
  full_name='game.LoginResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_info', full_name='game.LoginResp.user_info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='balance', full_name='game.LoginResp.balance', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='token', full_name='game.LoginResp.token', index=2,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='refresh_token', full_name='game.LoginResp.refresh_token', index=3,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=76,
  serialized_end=177,
)


_USERINFO = _descriptor.Descriptor(
  name='UserInfo',
  full_name='game.UserInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='game.UserInfo.user_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='account', full_name='game.UserInfo.account', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='nickname', full_name='game.UserInfo.nickname', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='gender', full_name='game.UserInfo.gender', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=179,
  serialized_end=271,
)


_REGISTERREQ = _descriptor.Descriptor(
  name='RegisterReq',
  full_name='game.RegisterReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='account', full_name='game.RegisterReq.account', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='password', full_name='game.RegisterReq.password', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='nickname', full_name='game.RegisterReq.nickname', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='gender', full_name='game.RegisterReq.gender', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=273,
  serialized_end=369,
)


_REGISTERRESP = _descriptor.Descriptor(
  name='RegisterResp',
  full_name='game.RegisterResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='game.RegisterResp.user_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=371,
  serialized_end=402,
)


_GETONLINEUSERSREQ = _descriptor.Descriptor(
  name='GetOnlineUsersReq',
  full_name='game.GetOnlineUsersReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=404,
  serialized_end=423,
)


_GETONLINEUSERSRESP = _descriptor.Descriptor(
  name='GetOnlineUsersResp',
  full_name='game.GetOnlineUsersResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='users', full_name='game.GetOnlineUsersResp.users', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=425,
  serialized_end=476,
)


_BATTLEMSG = _descriptor.Descriptor(
  name='BattleMsg',
  full_name='game.BattleMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg_type', full_name='game.BattleMsg.msg_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='content', full_name='game.BattleMsg.content', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _BATTLEMSG_BATTLEMSGTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=478,
  serialized_end=603,
)


_BATTLELITEREQ = _descriptor.Descriptor(
  name='BattleLiteReq',
  full_name='game.BattleLiteReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='target_uid', full_name='game.BattleLiteReq.target_uid', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=605,
  serialized_end=640,
)


_BATTLELITERESP = _descriptor.Descriptor(
  name='BattleLiteResp',
  full_name='game.BattleLiteResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='game.BattleLiteResp.msg', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=642,
  serialized_end=688,
)

_LOGINRESP.fields_by_name['user_info'].message_type = _USERINFO
_USERINFO.fields_by_name['gender'].enum_type = _GENDER
_REGISTERREQ.fields_by_name['gender'].enum_type = _GENDER
_GETONLINEUSERSRESP.fields_by_name['users'].message_type = _USERINFO
_BATTLEMSG.fields_by_name['msg_type'].enum_type = _BATTLEMSG_BATTLEMSGTYPE
_BATTLEMSG_BATTLEMSGTYPE.containing_type = _BATTLEMSG
_BATTLELITERESP.fields_by_name['msg'].message_type = _BATTLEMSG
DESCRIPTOR.message_types_by_name['LoginReq'] = _LOGINREQ
DESCRIPTOR.message_types_by_name['LoginResp'] = _LOGINRESP
DESCRIPTOR.message_types_by_name['UserInfo'] = _USERINFO
DESCRIPTOR.message_types_by_name['RegisterReq'] = _REGISTERREQ
DESCRIPTOR.message_types_by_name['RegisterResp'] = _REGISTERRESP
DESCRIPTOR.message_types_by_name['GetOnlineUsersReq'] = _GETONLINEUSERSREQ
DESCRIPTOR.message_types_by_name['GetOnlineUsersResp'] = _GETONLINEUSERSRESP
DESCRIPTOR.message_types_by_name['BattleMsg'] = _BATTLEMSG
DESCRIPTOR.message_types_by_name['BattleLiteReq'] = _BATTLELITEREQ
DESCRIPTOR.message_types_by_name['BattleLiteResp'] = _BATTLELITERESP
DESCRIPTOR.enum_types_by_name['Gender'] = _GENDER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LoginReq = _reflection.GeneratedProtocolMessageType('LoginReq', (_message.Message,), {
  'DESCRIPTOR' : _LOGINREQ,
  '__module__' : 'protocol.game_pb2'
  # @@protoc_insertion_point(class_scope:game.LoginReq)
  })
_sym_db.RegisterMessage(LoginReq)

LoginResp = _reflection.GeneratedProtocolMessageType('LoginResp', (_message.Message,), {
  'DESCRIPTOR' : _LOGINRESP,
  '__module__' : 'protocol.game_pb2'
  # @@protoc_insertion_point(class_scope:game.LoginResp)
  })
_sym_db.RegisterMessage(LoginResp)

UserInfo = _reflection.GeneratedProtocolMessageType('UserInfo', (_message.Message,), {
  'DESCRIPTOR' : _USERINFO,
  '__module__' : 'protocol.game_pb2'
  # @@protoc_insertion_point(class_scope:game.UserInfo)
  })
_sym_db.RegisterMessage(UserInfo)

RegisterReq = _reflection.GeneratedProtocolMessageType('RegisterReq', (_message.Message,), {
  'DESCRIPTOR' : _REGISTERREQ,
  '__module__' : 'protocol.game_pb2'
  # @@protoc_insertion_point(class_scope:game.RegisterReq)
  })
_sym_db.RegisterMessage(RegisterReq)

RegisterResp = _reflection.GeneratedProtocolMessageType('RegisterResp', (_message.Message,), {
  'DESCRIPTOR' : _REGISTERRESP,
  '__module__' : 'protocol.game_pb2'
  # @@protoc_insertion_point(class_scope:game.RegisterResp)
  })
_sym_db.RegisterMessage(RegisterResp)

GetOnlineUsersReq = _reflection.GeneratedProtocolMessageType('GetOnlineUsersReq', (_message.Message,), {
  'DESCRIPTOR' : _GETONLINEUSERSREQ,
  '__module__' : 'protocol.game_pb2'
  # @@protoc_insertion_point(class_scope:game.GetOnlineUsersReq)
  })
_sym_db.RegisterMessage(GetOnlineUsersReq)

GetOnlineUsersResp = _reflection.GeneratedProtocolMessageType('GetOnlineUsersResp', (_message.Message,), {
  'DESCRIPTOR' : _GETONLINEUSERSRESP,
  '__module__' : 'protocol.game_pb2'
  # @@protoc_insertion_point(class_scope:game.GetOnlineUsersResp)
  })
_sym_db.RegisterMessage(GetOnlineUsersResp)

BattleMsg = _reflection.GeneratedProtocolMessageType('BattleMsg', (_message.Message,), {
  'DESCRIPTOR' : _BATTLEMSG,
  '__module__' : 'protocol.game_pb2'
  # @@protoc_insertion_point(class_scope:game.BattleMsg)
  })
_sym_db.RegisterMessage(BattleMsg)

BattleLiteReq = _reflection.GeneratedProtocolMessageType('BattleLiteReq', (_message.Message,), {
  'DESCRIPTOR' : _BATTLELITEREQ,
  '__module__' : 'protocol.game_pb2'
  # @@protoc_insertion_point(class_scope:game.BattleLiteReq)
  })
_sym_db.RegisterMessage(BattleLiteReq)

BattleLiteResp = _reflection.GeneratedProtocolMessageType('BattleLiteResp', (_message.Message,), {
  'DESCRIPTOR' : _BATTLELITERESP,
  '__module__' : 'protocol.game_pb2'
  # @@protoc_insertion_point(class_scope:game.BattleLiteResp)
  })
_sym_db.RegisterMessage(BattleLiteResp)


DESCRIPTOR._options = None

_GAME = _descriptor.ServiceDescriptor(
  name='Game',
  full_name='game.Game',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=736,
  serialized_end=910,
  methods=[
  _descriptor.MethodDescriptor(
    name='Login',
    full_name='game.Game.Login',
    index=0,
    containing_service=None,
    input_type=_LOGINREQ,
    output_type=_LOGINRESP,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Register',
    full_name='game.Game.Register',
    index=1,
    containing_service=None,
    input_type=_REGISTERREQ,
    output_type=_REGISTERRESP,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetOnlineUsers',
    full_name='game.Game.GetOnlineUsers',
    index=2,
    containing_service=None,
    input_type=_GETONLINEUSERSREQ,
    output_type=_GETONLINEUSERSRESP,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_GAME)

DESCRIPTOR.services_by_name['Game'] = _GAME


_BATTLE = _descriptor.ServiceDescriptor(
  name='Battle',
  full_name='game.Battle',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=912,
  serialized_end=979,
  methods=[
  _descriptor.MethodDescriptor(
    name='BattleLite',
    full_name='game.Battle.BattleLite',
    index=0,
    containing_service=None,
    input_type=_BATTLELITEREQ,
    output_type=_BATTLELITERESP,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_BATTLE)

DESCRIPTOR.services_by_name['Battle'] = _BATTLE

# @@protoc_insertion_point(module_scope)
